# Generated by Django 3.1.7 on 2021-03-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210228_2038'),
        ('carts', '0003_auto_20210307_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('item', 'cart')},
        ),
    ]
