# Generated by Django 3.1.7 on 2021-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
    ]
