# Generated by Django 3.1.7 on 2021-02-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210228_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to='items', width_field='width_field'),
        ),
    ]
