# Generated by Django 3.1.7 on 2021-02-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210228_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('MO', 'на модерации'), ('PU', 'опубликован'),
                                            ('RE', 'отклонен')], default='MO', max_length=13),
        ),
    ]
