# Generated by Django 3.1.7 on 2021-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210313_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(default=None),
        ),
    ]
