# Generated by Django 3.1.7 on 2021-03-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210315_1259'),
        ('orders', '0004_auto_20210313_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.cart'),
        ),
    ]
